### ISSUE TITLE
ChatBot API Overview

### ISSUE THREAD

**Issue by princebansal** [GDGVIT/Devfest-Android-16#1]
@shubham0704 Please edit the wiki and put up the API reference of Chatbot and FAQs. Please follow the same format as with others.

**Comment by abhinav-adtechs** [comment]
Ya give me fast, I will integrate and sleep fast fast

**Comment by shubham0704** [comment]
Done

**Comment by princebansal** [comment]
@shubham0704 You just overwrote the previous FAQ API. Please restore it and make a different section with title "Chatbot" and detail your API there. The previous FAQ API is used in the app.

**Comment by shubham0704** [comment]
Done
