### ISSUE TITLE
Navigation tabs out of sync

### ISSUE THREAD

**Issue by twhetzel** [GDGVIT/Devfest-Android-16#3]
Using the bottom navigation row to scroll through the schedule, if an event time slot is selected and the top panel is displaying the details information it is not updated. If the top panel is displaying the title details, clicking on the navigation item in the bottom row does update the top panel.

**Comment by princebansal** [comment]
Thanks for reporting. I will look over that.

**Comment by princebansal** [comment]
The issue is resolved. Please have a look. I will update app on Play Store with other improvements. Till that you can clone and check out the current updates.
